language: python
# command to install dependencies
install:
  - pip install tox
  - pip install coveralls
# run tests
script:
  - tox -e py26
  - tox -e py27
  - tox -e lint
after_success:
  - tox -e cover
  - coveralls
  - scripts/merge.sh
