language: python

install:
  - scripts/custom_pip_install.sh tox

script:
  - tox -e py26
  - tox -e py27
  - tox -e lint
  - tox -e regression
  - scripts/update_docs.sh
after_success:
  - tox -e coveralls
